openapi: 3.1.1
info:
  title: Multi-LLM Answers API
  version: 1.0.0
servers:
  - url: https://llmevaluator-chatgpt.onrender.com
paths:
  /responses:
    post:
      summary: Get responses from multiple LLMs
      operationId: getResponses
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LlmRequest'
      responses:
        '200':
          description: Responses from models
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LlmResponsesModel'
components:
  schemas:
    LlmRequest:
      type: object
      required:
        - question
        - prompt_template_name
        - models
      properties:
        question:
          type: string
          description: "The user question"
        prompt_template_name:
          type: string
          description: "Name of the prompt template"
        models:
          type: object
          description: "Dictionary of model names and IDs to query"
          additionalProperties:
            type: string
    LlmResponsesModel:
      type: object
      properties:
        prompt:
          type: string
        llm_responses:
          type: array
          items:
            type: object
            properties:
              llm:
                type: string
              response:
                type: string
