models:
  openrouter_deepseek: deepseek/deepseek-chat-v3.1:free
  openrouter_nvidia: nvidia/nemotron-nano-9b-v2:free
  openrouter_openai: openai/gpt-oss-20b:free
  local: gemma:2b

evaluator:
  openrouter_nvidia: nvidia/nemotron-nano-9b-v2:free

reasoning_strategies:
  CoT: |
    Use this systematic approach to provide your response:
    1. Break down the problem into smaller steps
    2. Address each step systematically
    3. Show your reasoning for each step
    4. Then provide your final response

  ReAct: |
    Use this systematic approach to provide your response:
    1. Thought: What approaches could I take to solve this?
    2. Action: Choose and implement the best approach
    3. Observation: What happened? What did I learn?
    4. Reflection: Do I have enough information to provide my final answer, or should I try a different approach?

    (Repeat steps 1–4 as needed)

    Then provide your final answer.

  Self-Ask: |
    Use this systematic approach to provide your response:
    1. Break the main question into smaller sub-questions.
    2. Answer each sub-question thoroughly.
    3. Then, based on those answers, synthesize a clear and thoughtful final response.
    
